# Generated by Django 3.1.7 on 2021-03-16 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_auto_20210316_1444'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='tag',
        ),
        migrations.AddField(
            model_name='tag',
            name='note',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='notes.note'),
        ),
    ]
