# Generated by Django 3.1.7 on 2021-03-22 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0005_note_tagname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='tagName',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='note',
        ),
        migrations.AddField(
            model_name='note',
            name='tag',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='notes.tag'),
        ),
    ]
